### ISSUE TITLE
Getting mismatched device error on running the api more than once

### ISSUE THREAD

**Issue by amanjain1397appy** [pablodawson/controlnet-depth#1]
I have build the docker image from this repo and hosted the api also. When I try to run the prediction the first time using the code you have provided in _test.py_ it works just fine. However the second time I run the same api, I get the following error.

```
Traceback (most recent call last):
  File "handle_request", line 81, in handle_request
    FutureStatic,
  File "//server.py", line 36, in inference
    output = user_src.inference(model_inputs)
  File "/app.py", line 74, in inference
    output = model(
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_controlnet.py", line 779, in __call__
    latents = self.scheduler.step(noise_pred, t, latents, **extra_step_kwargs).prev_sample
  File "/opt/conda/lib/python3.10/site-packages/diffusers/schedulers/scheduling_unipc_multistep.py", line 526, in step
    model_output_convert = self.convert_model_output(model_output, timestep, sample)
  File "/opt/conda/lib/python3.10/site-packages/diffusers/schedulers/scheduling_unipc_multistep.py", line 231, in convert_model_output
    x0_pred = (sample - sigma_t * model_output) / alpha_t
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

I am using the following code snippet to make the api call. 

```
import base64
from io import BytesIO
import requests
from PIL import Image

img_name = "./data/cat.jpg"
with open(img_name, "rb") as f:
    bytes = f.read()
    encoded = base64.b64encode(bytes).decode('utf-8')

model_inputs = {
    'prompt': 'cute cat best quality, extremely detailed',
    'negative_prompt': 'monochrome, lowres, bad anatomy, worst quality, low quality',
    'num_inference_steps': 20,
    'image_data': encoded
}

res = requests.post('http://localhost:8000/', json = model_inputs)
```

I built and run the container using the following snippet 

```
sudo docker build -t control-depth .
docker run -it -p 8000:8000 --gpus all control-depth
```

 
Can you please help me out with this?

**Comment by pablodawson** [comment]
Hey, thanks for reporting.

I could reproduce this too, looks like the optimizations take the model out of gpu memory.
Just pushed a version without those, at least locally it works fine for me. I'll see how it goes deployed.

**Comment by amanjain1397appy** [comment]
Hi, I tried out the latest commit. It seems to be working now on multiple api hits , but as suspected the vram utilisation is a lot more now. Earlier when the memory optimisation code was in place, the process took about 3.5 GB vram, but now it gone up to 9 GB. 

I am still unaware how this works out.

**Comment by amanjain1397appy** [comment]
Also, during your previous commit having when the memory optimisation code was in place, I still had about 10 GB VRAM free after the first api call. As I mentioned, inference only took about 3.5 gb gpu memory, so 10 GB somehow wasnt enough for the second api call?

**Comment by pablodawson** [comment]
I don't know the details of how the optimizations work either, I suspect it was not a VRAM issue though. For the target (A100) I don't think this is much of a problem anyways.
